#!/bin/bash
#
# Get our network information from the DO Metadata service
# Copyright (C) 2018 Chris Blake <chrisrblake93@gmail.com>
#

case "$1" in
	start)
		echo -n "Attempting to auto-configure networking"
		# First bring up eth0 with a link-local IP so we can get our info
		/usr/sbin/avahi-autoipd -c eth0
		if [ $? != 0 ]; then
			/usr/sbin/avahi-autoipd --force-bind -w -D eth0
		fi

		# Verify we can get our metadata, if not, make sure we safely exit
		counter=0
		while true; do
			METADATAJSON=$(wget -T 5 -q -O- http://169.254.169.254/metadata/v1.json 2> /dev/null)
			if [ -z "$METADATAJSON" ]; then
				if [ $counter -gt 5 ]; then
					echo -e "\nUnable to hit metadata endpoint!"
					/usr/sbin/avahi-autoipd -k eth0
					ip link set eth0 down
					ip addr flush dev eth0
					exit 0
				fi
				echo -n "."
				let "counter++"
				sleep $counter # So we increase our sleep with the counter
			else
				break
			fi
		done

		# Configure our hostname
		DOHOSTNAME=$(wget -qO- http://169.254.169.254/metadata/v1/hostname 2> /dev/null)
		echo "$DOHOSTNAME" > /etc/hostname
		echo "$DOHOSTNAME" > /proc/sys/kernel/hostname

		# Pull down networking configuration
		DOIP=$(wget -qO- http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address 2> /dev/null)
		DONETMASK=$(wget -qO- http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/netmask 2> /dev/null)
		DOGATEWAY=$(wget -qO- http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/gateway 2> /dev/null)

		# Generate our network config file for when we bring the int up properly
		echo "auto eth0" > /tmp/eth0.int
		echo "iface eth0 inet static" >> /tmp/eth0.int
		echo -e "\taddress $DOIP" >> /tmp/eth0.int
		echo -e "\tnetmask $DONETMASK" >> /tmp/eth0.int
		echo -e "\tgateway $DOGATEWAY" >> /tmp/eth0.int

		# Do we have IPv6?
		DOIP6=$(wget -qO- http://169.254.169.254/metadata/v1/interfaces/public/0/ipv6/address 2> /dev/null)
		if [ "$DOIP6" != "not found" ]; then
			DOCIDR6=$(wget -qO- http://169.254.169.254/metadata/v1/interfaces/public/0/ipv6/cidr 2> /dev/null)
			DOGATEWAY6=$(wget -qO- http://169.254.169.254/metadata/v1/interfaces/public/0/ipv6/gateway 2> /dev/null)
			echo -e "iface eth0 inet6 static" >> /tmp/eth0.int
			echo -e "\taddress $DOIP6" >> /tmp/eth0.int
			echo -e "\tnetmask $DOCIDR6" >> /tmp/eth0.int
			echo -e "\tgateway $DOGATEWAY6" >> /tmp/eth0.int
		fi

		# Config DNS
		while read -r line; do
    		echo "nameserver $line" >> /etc/resolv.conf
		done <<< "$(wget -qO- http://169.254.169.254/metadata/v1/dns/nameservers 2> /dev/null)"

		# Configure SSH keys
		mkdir -p /root/.ssh
		wget -qO /root/.ssh/authorized_keys http://169.254.169.254/metadata/v1/public-keys 2> /dev/null
		chmod 700 /root/.ssh
		chmod -R 600 /root/.ssh/*

		# Tear the int down
		/usr/sbin/avahi-autoipd -k eth0
		ip link set eth0 down
		ip addr flush dev eth0

		# Now that our config exists, bring the int up the proper way
		/sbin/ifup -a
		;;
	stop)
		echo "" # We do nothing lolol
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac

exit $?
